apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: gnachev/nginx-sap-test-project:TAG
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - test -f /run/nginx.pid && ps -ef | grep nginx
          initialDelaySeconds: 5
          periodSeconds: 5        
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1        
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 128m
            memory: 96Mi
