apiVersion:1 apps/v1
kind:1 Deployment
metadata:1
  name:1 hello-world-nginx
  labels:1
    app:1 hello-world-nginx
spec:1
  replicas:1 2
  selector:1
    matchLabels:1
      app:1 hello-world-nginx
  template:1
    metadata:1
      labels:1
        app:1 hello-world-nginx
    spec:1
      containers:1
      - name:1 hello-world-nginx
        image:1 gnachev/nginx-sap-test-project:1replaceImageTag
        ports:1
        - containerPort:1 8080
