apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: nginx-ingress 
spec: 
  ingressClassName: nginx 
  rules: 
    - host: hello-world.info
      http: 
        paths: 
          - backend: 
              service: 
                name: nginx-service
                port: 
                  number: 80
            path: / 
            pathType: Prefix 
