apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sap-cicd-lab
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-app
